// Generated by tools/gen_ui.py from assets/resources/ui/*/uilayout.json. Do not edit.
// paths: part id -> node path in the prefab;
// states: node path -> state -> SpriteFrame resource dir; bars: fill node path -> full width.

export interface UiGenEntry {
    prefab: string;
    nodes: number;
    paths: Record<string, string>;
    states: Record<string, Record<string, string>>;
    bars: Record<string, number>;
}

export const UI_GEN: Record<string, UiGenEntry> = {
    "BattleHud": {
        "prefab": "prefabs/ui/BattleHud",
        "nodes": 91,
        "paths": {
            "fx.ScreenFlash": "Fx/ScreenFlash",
            "fx.CutIn": "Fx/CutIn",
            "fx.CutIn/Text": "Fx/CutIn/Text",
            "fx.PopEnemy": "Fx/PopEnemy",
            "fx.PopPlayer": "Fx/PopPlayer",
            "top_block": "top_block",
            "titlebar": "top_block/titlebar",
            "title": "top_block/titlebar/title",
            "hazard_top": "top_block/hazard_top",
            "enemy_panel": "top_block/enemy_panel",
            "enemy_name": "top_block/enemy_panel/enemy_name",
            "enemy_lv": "top_block/enemy_panel/enemy_lv",
            "enemy_lv_chip": "top_block/enemy_panel/enemy_lv/enemy_lv_chip",
            "enemy_lv_chip.text": "top_block/enemy_panel/enemy_lv/enemy_lv_chip/Text",
            "enemy_hp_pct": "top_block/enemy_panel/enemy_hp_pct",
            "enemy_hp_label": "top_block/enemy_panel/enemy_hp_label",
            "enemy_hp_track": "top_block/enemy_panel/enemy_hp_track",
            "enemy_hp_track_fill": "top_block/enemy_panel/enemy_hp_track/enemy_hp_track_fill",
            "enemy_hp": "top_block/enemy_panel/enemy_hp",
            "enemy_spike": "top_block/enemy_panel/enemy_spike",
            "enemy_slash": "top_block/enemy_panel/enemy_slash",
            "settings": "top_block/settings",
            "settings_rim": "top_block/settings/settings_rim",
            "settings_face": "top_block/settings/settings_face",
            "settings_label": "top_block/settings/settings_label",
            "stage_view": "stage_view",
            "bottom_block": "bottom_block",
            "skill_grid": "bottom_block/skill_grid",
            "move_0": "bottom_block/skill_grid/move_0",
            "move_0_rim": "bottom_block/skill_grid/move_0/move_0_rim",
            "move_0_face": "bottom_block/skill_grid/move_0/move_0_face",
            "move_0_name": "bottom_block/skill_grid/move_0/move_0_name",
            "move_pp_0": "bottom_block/skill_grid/move_0/move_pp_0",
            "move_mp_0": "bottom_block/skill_grid/move_0/move_mp_0",
            "move_1": "bottom_block/skill_grid/move_1",
            "move_1_rim": "bottom_block/skill_grid/move_1/move_1_rim",
            "move_1_face": "bottom_block/skill_grid/move_1/move_1_face",
            "move_1_name": "bottom_block/skill_grid/move_1/move_1_name",
            "move_pp_1": "bottom_block/skill_grid/move_1/move_pp_1",
            "move_mp_1": "bottom_block/skill_grid/move_1/move_mp_1",
            "move_2": "bottom_block/skill_grid/move_2",
            "move_2_rim": "bottom_block/skill_grid/move_2/move_2_rim",
            "move_2_face": "bottom_block/skill_grid/move_2/move_2_face",
            "move_2_name": "bottom_block/skill_grid/move_2/move_2_name",
            "move_pp_2": "bottom_block/skill_grid/move_2/move_pp_2",
            "move_mp_2": "bottom_block/skill_grid/move_2/move_mp_2",
            "move_3": "bottom_block/skill_grid/move_3",
            "move_3_rim": "bottom_block/skill_grid/move_3/move_3_rim",
            "move_3_face": "bottom_block/skill_grid/move_3/move_3_face",
            "move_3_name": "bottom_block/skill_grid/move_3/move_3_name",
            "move_pp_3": "bottom_block/skill_grid/move_3/move_pp_3",
            "move_mp_3": "bottom_block/skill_grid/move_3/move_mp_3",
            "ult_spike": "bottom_block/skill_grid/ult_spike",
            "util_row": "bottom_block/util_row",
            "hazard_bottom": "bottom_block/util_row/hazard_bottom",
            "bag": "bottom_block/util_row/bag",
            "bag_rim": "bottom_block/util_row/bag/bag_rim",
            "bag_face": "bottom_block/util_row/bag/bag_face",
            "bag_label": "bottom_block/util_row/bag/bag_label",
            "run": "bottom_block/util_row/run",
            "run_rim": "bottom_block/util_row/run/run_rim",
            "run_face": "bottom_block/util_row/run/run_face",
            "run_label": "bottom_block/util_row/run/run_label",
            "party": "bottom_block/util_row/party",
            "party_rim": "bottom_block/util_row/party/party_rim",
            "party_face": "bottom_block/util_row/party/party_face",
            "party_label": "bottom_block/util_row/party/party_label",
            "party_count": "bottom_block/util_row/party/party_count",
            "catch": "bottom_block/util_row/catch",
            "catch_rim": "bottom_block/util_row/catch/catch_rim",
            "catch_face": "bottom_block/util_row/catch/catch_face",
            "catch_label": "bottom_block/util_row/catch/catch_label",
            "player_panel": "bottom_block/player_panel",
            "player_name": "bottom_block/player_panel/player_name",
            "player_lv": "bottom_block/player_panel/player_lv",
            "player_lv_chip": "bottom_block/player_panel/player_lv/player_lv_chip",
            "player_lv_chip.text": "bottom_block/player_panel/player_lv/player_lv_chip/Text",
            "player_hp_pct": "bottom_block/player_panel/player_hp_pct",
            "player_hp_label": "bottom_block/player_panel/player_hp_label",
            "player_hp_track": "bottom_block/player_panel/player_hp_track",
            "player_hp_track_fill": "bottom_block/player_panel/player_hp_track/player_hp_track_fill",
            "player_hp": "bottom_block/player_panel/player_hp",
            "player_mp_label": "bottom_block/player_panel/player_mp_label",
            "player_mp_track": "bottom_block/player_panel/player_mp_track",
            "player_mp_track_fill": "bottom_block/player_panel/player_mp_track/player_mp_track_fill",
            "player_mp": "bottom_block/player_panel/player_mp",
            "status_bar": "bottom_block/status_bar",
            "status": "bottom_block/status_bar/status",
            "status_slash": "bottom_block/status_bar/status_slash"
        },
        "states": {
            "top_block/settings/settings_rim": {
                "normal": "ui/battle/util_rim__216x112__normal",
                "pressed": "ui/battle/util_rim__216x112__pressed",
                "disabled": "ui/battle/util_rim__216x112__disabled"
            },
            "top_block/settings/settings_face": {
                "normal": "ui/battle/util_face__196x92__normal",
                "disabled": "ui/battle/util_face__196x92__disabled"
            },
            "bottom_block/skill_grid/move_0/move_0_rim": {
                "normal": "ui/battle/skill_rim__672x144__normal",
                "pressed": "ui/battle/skill_rim__672x144__pressed",
                "disabled": "ui/battle/skill_rim__672x144__disabled"
            },
            "bottom_block/skill_grid/move_0/move_0_face": {
                "normal": "ui/battle/skill_face__648x120__normal",
                "disabled": "ui/battle/skill_face__648x120__disabled"
            },
            "bottom_block/skill_grid/move_1/move_1_rim": {
                "normal": "ui/battle/skill_rim__672x144__normal",
                "pressed": "ui/battle/skill_rim__672x144__pressed",
                "disabled": "ui/battle/skill_rim__672x144__disabled"
            },
            "bottom_block/skill_grid/move_1/move_1_face": {
                "normal": "ui/battle/skill_face__648x120__normal",
                "disabled": "ui/battle/skill_face__648x120__disabled"
            },
            "bottom_block/skill_grid/move_2/move_2_rim": {
                "normal": "ui/battle/skill_rim__672x144__normal",
                "pressed": "ui/battle/skill_rim__672x144__pressed",
                "disabled": "ui/battle/skill_rim__672x144__disabled"
            },
            "bottom_block/skill_grid/move_2/move_2_face": {
                "normal": "ui/battle/skill_face__648x120__normal",
                "disabled": "ui/battle/skill_face__648x120__disabled"
            },
            "bottom_block/skill_grid/move_3/move_3_rim": {
                "normal": "ui/battle/skill_rim__672x144__normal",
                "pressed": "ui/battle/skill_rim__672x144__pressed",
                "disabled": "ui/battle/skill_rim__672x144__disabled"
            },
            "bottom_block/skill_grid/move_3/move_3_face": {
                "normal": "ui/battle/skill_face__648x120__normal",
                "disabled": "ui/battle/skill_face__648x120__disabled"
            },
            "bottom_block/util_row/bag/bag_rim": {
                "normal": "ui/battle/util_rim__272x144__normal",
                "pressed": "ui/battle/util_rim__272x144__pressed",
                "disabled": "ui/battle/util_rim__272x144__disabled"
            },
            "bottom_block/util_row/bag/bag_face": {
                "normal": "ui/battle/util_face__252x124__normal",
                "disabled": "ui/battle/util_face__252x124__disabled"
            },
            "bottom_block/util_row/run/run_rim": {
                "normal": "ui/battle/util_rim__272x144__normal",
                "pressed": "ui/battle/util_rim__272x144__pressed",
                "disabled": "ui/battle/util_rim__272x144__disabled"
            },
            "bottom_block/util_row/run/run_face": {
                "normal": "ui/battle/util_face__252x124__normal",
                "disabled": "ui/battle/util_face__252x124__disabled"
            },
            "bottom_block/util_row/party/party_rim": {
                "normal": "ui/battle/util_rim__320x144__normal",
                "pressed": "ui/battle/util_rim__320x144__pressed",
                "disabled": "ui/battle/util_rim__320x144__disabled"
            },
            "bottom_block/util_row/party/party_face": {
                "normal": "ui/battle/util_face__300x124__normal",
                "disabled": "ui/battle/util_face__300x124__disabled"
            },
            "bottom_block/util_row/catch/catch_rim": {
                "normal": "ui/battle/skill_rim__464x144__normal",
                "pressed": "ui/battle/skill_rim__464x144__pressed",
                "disabled": "ui/battle/skill_rim__464x144__disabled"
            },
            "bottom_block/util_row/catch/catch_face": {
                "normal": "ui/battle/skill_face__440x120__normal",
                "disabled": "ui/battle/skill_face__440x120__disabled"
            }
        },
        "bars": {
            "top_block/enemy_panel/enemy_hp_track/enemy_hp_track_fill": 828.0,
            "bottom_block/player_panel/player_hp_track/player_hp_track_fill": 828.0,
            "bottom_block/player_panel/player_mp_track/player_mp_track_fill": 828.0
        }
    },
    "BagDialog": {
        "prefab": "prefabs/ui/BagDialog",
        "nodes": 38,
        "paths": {
            "dim": "Dim",
            "bag_dialog": "bag_dialog",
            "dlg_body": "bag_dialog/dlg_body",
            "title_wedge": "bag_dialog/title_wedge",
            "item_list": "bag_dialog/item_list",
            "item_row_0": "bag_dialog/item_list/item_row_0",
            "item_row_0_panel": "bag_dialog/item_list/item_row_0/item_row_0_panel",
            "item_name_0": "bag_dialog/item_list/item_row_0/item_name_0",
            "item_count_0": "bag_dialog/item_list/item_row_0/item_count_0",
            "item_count_0_chip": "bag_dialog/item_list/item_row_0/item_count_0/item_count_0_chip",
            "item_count_0.text": "bag_dialog/item_list/item_row_0/item_count_0/Text",
            "item_desc_0": "bag_dialog/item_list/item_row_0/item_desc_0",
            "item_use_0": "bag_dialog/item_list/item_row_0/item_use_0",
            "item_use_0_rim": "bag_dialog/item_list/item_row_0/item_use_0/item_use_0_rim",
            "item_use_0_face": "bag_dialog/item_list/item_row_0/item_use_0/item_use_0_face",
            "item_use_0_label": "bag_dialog/item_list/item_row_0/item_use_0/item_use_0_label",
            "item_row_1": "bag_dialog/item_list/item_row_1",
            "item_row_1_panel": "bag_dialog/item_list/item_row_1/item_row_1_panel",
            "item_name_1": "bag_dialog/item_list/item_row_1/item_name_1",
            "item_count_1": "bag_dialog/item_list/item_row_1/item_count_1",
            "item_count_1_chip": "bag_dialog/item_list/item_row_1/item_count_1/item_count_1_chip",
            "item_count_1.text": "bag_dialog/item_list/item_row_1/item_count_1/Text",
            "item_desc_1": "bag_dialog/item_list/item_row_1/item_desc_1",
            "item_use_1": "bag_dialog/item_list/item_row_1/item_use_1",
            "item_use_1_rim": "bag_dialog/item_list/item_row_1/item_use_1/item_use_1_rim",
            "item_use_1_face": "bag_dialog/item_list/item_row_1/item_use_1/item_use_1_face",
            "item_use_1_label": "bag_dialog/item_list/item_row_1/item_use_1/item_use_1_label",
            "title_panel": "bag_dialog/title_panel",
            "bag_title": "bag_dialog/title_panel/bag_title",
            "hazard_band": "bag_dialog/hazard_band",
            "bag_hint": "bag_dialog/bag_hint",
            "bag_close": "bag_dialog/bag_close",
            "bag_close_rim": "bag_dialog/bag_close/bag_close_rim",
            "bag_close_face": "bag_dialog/bag_close/bag_close_face",
            "bag_close_label": "bag_dialog/bag_close/bag_close_label",
            "spike_tl": "bag_dialog/spike_tl",
            "spike_br": "bag_dialog/spike_br"
        },
        "states": {
            "bag_dialog/item_list/item_row_0/item_use_0/item_use_0_rim": {
                "normal": "ui/bag/skill_rim__280x144__normal",
                "pressed": "ui/bag/skill_rim__280x144__pressed",
                "disabled": "ui/bag/skill_rim__280x144__disabled"
            },
            "bag_dialog/item_list/item_row_0/item_use_0/item_use_0_face": {
                "normal": "ui/bag/skill_face__256x120__normal",
                "disabled": "ui/bag/skill_face__256x120__disabled"
            },
            "bag_dialog/item_list/item_row_1/item_use_1/item_use_1_rim": {
                "normal": "ui/bag/skill_rim__280x144__normal",
                "pressed": "ui/bag/skill_rim__280x144__pressed",
                "disabled": "ui/bag/skill_rim__280x144__disabled"
            },
            "bag_dialog/item_list/item_row_1/item_use_1/item_use_1_face": {
                "normal": "ui/bag/skill_face__256x120__normal",
                "disabled": "ui/bag/skill_face__256x120__disabled"
            },
            "bag_dialog/bag_close/bag_close_rim": {
                "normal": "ui/bag/util_rim__480x128__normal",
                "pressed": "ui/bag/util_rim__480x128__pressed",
                "disabled": "ui/bag/util_rim__480x128__disabled"
            },
            "bag_dialog/bag_close/bag_close_face": {
                "normal": "ui/bag/util_face__460x108__normal",
                "disabled": "ui/bag/util_face__460x108__disabled"
            }
        },
        "bars": {}
    },
    "ResultDialog": {
        "prefab": "prefabs/ui/ResultDialog",
        "nodes": 23,
        "paths": {
            "dim": "Dim",
            "result_dialog": "result_dialog",
            "dialog_plate": "result_dialog/dialog_plate",
            "title_slash": "result_dialog/title_slash",
            "sub_bar": "result_dialog/sub_bar",
            "result_sub": "result_dialog/sub_bar/result_sub",
            "lines_panel": "result_dialog/lines_panel",
            "lines_tag": "result_dialog/lines_panel/lines_tag",
            "lines_tag.text": "result_dialog/lines_panel/lines_tag/Text",
            "result_line_0": "result_dialog/lines_panel/result_line_0",
            "lines_rule": "result_dialog/lines_panel/lines_rule",
            "result_line_1": "result_dialog/lines_panel/result_line_1",
            "lines_hazard": "result_dialog/lines_hazard",
            "spike_bl": "result_dialog/spike_bl",
            "spike_br": "result_dialog/spike_br",
            "title_banner": "result_dialog/title_banner",
            "result_title": "result_dialog/title_banner/result_title",
            "result_next": "result_dialog/result_next",
            "next_rim": "result_dialog/result_next/next_rim",
            "next_face": "result_dialog/result_next/next_face",
            "next_label": "result_dialog/result_next/next_label",
            "next_arrow": "result_dialog/result_next/next_arrow"
        },
        "states": {
            "result_dialog/result_next/next_rim": {
                "normal": "ui/result/skill_rim__760x144__normal",
                "pressed": "ui/result/skill_rim__760x144__pressed",
                "disabled": "ui/result/skill_rim__760x144__disabled"
            },
            "result_dialog/result_next/next_face": {
                "normal": "ui/result/skill_face__736x120__normal",
                "disabled": "ui/result/skill_face__736x120__disabled"
            }
        },
        "bars": {}
    }
};
